FROM public.ecr.aws/lambda/python:3.12

WORKDIR ${LAMBDA_TASK_ROOT}

COPY requirements-sentiment.txt .
RUN pip install --no-cache-dir -r requirements-sentiment.txt

COPY pipelines ./pipelines
COPY lambda_handlers ./lambda_handlers

CMD ["lambda_handlers.sentiment_handler.lambda_handler"]