"""Enriched SQL models for metadata, transcript extraction

Revision ID: 9a0a89dc9b39
Revises: 1bf32db15257
Create Date: 2026-03-15 22:26:12.861433

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision = "9a0a89dc9b39"
down_revision = "1bf32db15257"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "narratives",
        sa.Column("narrative_id", sa.Uuid(), nullable=False),
        sa.Column(
            "narrative_label", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "narrative_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("narrative_id"),
    )
    op.create_table(
        "comments",
        sa.Column("video_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("comment_threads_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.video_id"],
        ),
        sa.PrimaryKeyConstraint("video_id"),
    )
    # Evolve transcripts before creating tables that reference transcript_id
    op.drop_table("insights")
    op.add_column("transcripts", sa.Column("transcript_id", sa.Uuid(), nullable=False))
    op.add_column(
        "transcripts", sa.Column("cleaned_transcript_txt", sa.Text(), nullable=False)
    )
    op.add_column(
        "transcripts", sa.Column("raw_transcript_json", sa.JSON(), nullable=False)
    )
    # Ensure transcript_id is uniquely identifiable for foreign key references
    op.create_unique_constraint(
        "uq_transcripts_transcript_id", "transcripts", ["transcript_id"]
    )
    # Preserve uniqueness on video_id if you still want one transcript per video
    op.create_unique_constraint("uq_transcripts_video_id", "transcripts", ["video_id"])
    op.drop_column("transcripts", "language")
    op.drop_column("transcripts", "content")
    op.drop_column("transcripts", "id")
    op.create_table(
        "claims",
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("video_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("transcript_id", sa.Uuid(), nullable=False),
        sa.Column("claim_text", sa.Text(), nullable=False),
        sa.Column("supporting_excerpt", sa.Text(), nullable=True),
        sa.Column("start_time_seconds", sa.Integer(), nullable=True),
        sa.Column("end_time_seconds", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["transcript_id"],
            ["transcripts.transcript_id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.video_id"],
        ),
        sa.PrimaryKeyConstraint("claim_id"),
    )
    op.create_table(
        "claim_narratives",
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("narrative_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.claim_id"],
        ),
        sa.ForeignKeyConstraint(
            ["narrative_id"],
            ["narratives.narrative_id"],
        ),
        sa.PrimaryKeyConstraint("claim_id", "narrative_id"),
    )
    op.add_column(
        "videos",
        sa.Column("channel_title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "videos",
        sa.Column("category_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column("videos", sa.Column("like_count", sa.BigInteger(), nullable=True))
    op.add_column("videos", sa.Column("comment_count", sa.BigInteger(), nullable=True))
    op.add_column("videos", sa.Column("duration_seconds", sa.Integer(), nullable=True))
    op.alter_column(
        "videos",
        "view_count",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        nullable=True,
    )
    op.drop_column("videos", "thumbnail_url")
    op.drop_column("videos", "stats")
    op.drop_column("videos", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "videos",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "videos",
        sa.Column(
            "stats",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "videos",
        sa.Column("thumbnail_url", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "videos",
        "view_count",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        nullable=False,
    )
    op.drop_column("videos", "duration_seconds")
    op.drop_column("videos", "comment_count")
    op.drop_column("videos", "like_count")
    op.drop_column("videos", "category_id")
    op.drop_column("videos", "channel_title")
    op.add_column(
        "transcripts", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False)
    )
    op.add_column(
        "transcripts",
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "transcripts",
        sa.Column("language", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "transcripts", type_="unique")
    op.drop_column("transcripts", "raw_transcript_json")
    op.drop_column("transcripts", "cleaned_transcript_txt")
    op.drop_column("transcripts", "transcript_id")
    op.create_table(
        "insights",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("video_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("model", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "claims",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "narratives",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "labels",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "confidence",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["video_id"], ["videos.video_id"], name=op.f("insights_video_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("insights_pkey")),
    )
    op.drop_table("claim_narratives")
    op.drop_table("claims")
    op.drop_table("comments")
    op.drop_table("narratives")
    # ### end Alembic commands ###
